/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Cuisine = IDL.Variant({
  'mediterranean' : IDL.Null,
  'thai' : IDL.Null,
  'japanese' : IDL.Null,
  'chinese' : IDL.Null,
  'mexican' : IDL.Null,
  'italian' : IDL.Null,
  'indian' : IDL.Null,
  'spanish' : IDL.Null,
  'american' : IDL.Null,
  'french' : IDL.Null,
});
export const Category = IDL.Variant({
  'sideDish' : IDL.Null,
  'mainCourse' : IDL.Null,
  'dessert' : IDL.Null,
  'soup' : IDL.Null,
  'salad' : IDL.Null,
  'appetizer' : IDL.Null,
  'beverage' : IDL.Null,
});
export const RecipeID = IDL.Nat;
export const Time = IDL.Int;
export const Recipe = IDL.Record({
  'id' : RecipeID,
  'photoAssetPath' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'descriptionHi' : IDL.Text,
  'createdAt' : Time,
  'cookTimeMinutes' : IDL.Nat,
  'stepsEn' : IDL.Vec(IDL.Text),
  'stepsHi' : IDL.Vec(IDL.Text),
  'cuisine' : Cuisine,
  'category' : Category,
  'prepTimeMinutes' : IDL.Nat,
  'servings' : IDL.Nat,
  'titleEn' : IDL.Text,
  'titleHi' : IDL.Text,
  'ingredientsEn' : IDL.Vec(IDL.Text),
  'ingredientsHi' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        Cuisine,
        Category,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [Recipe],
      [],
    ),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getRecipe' : IDL.Func([RecipeID], [Recipe], ['query']),
  'getRecipesByCategory' : IDL.Func([Category], [IDL.Vec(Recipe)], ['query']),
  'getRecipesByCuisine' : IDL.Func([Cuisine], [IDL.Vec(Recipe)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Cuisine = IDL.Variant({
    'mediterranean' : IDL.Null,
    'thai' : IDL.Null,
    'japanese' : IDL.Null,
    'chinese' : IDL.Null,
    'mexican' : IDL.Null,
    'italian' : IDL.Null,
    'indian' : IDL.Null,
    'spanish' : IDL.Null,
    'american' : IDL.Null,
    'french' : IDL.Null,
  });
  const Category = IDL.Variant({
    'sideDish' : IDL.Null,
    'mainCourse' : IDL.Null,
    'dessert' : IDL.Null,
    'soup' : IDL.Null,
    'salad' : IDL.Null,
    'appetizer' : IDL.Null,
    'beverage' : IDL.Null,
  });
  const RecipeID = IDL.Nat;
  const Time = IDL.Int;
  const Recipe = IDL.Record({
    'id' : RecipeID,
    'photoAssetPath' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'descriptionHi' : IDL.Text,
    'createdAt' : Time,
    'cookTimeMinutes' : IDL.Nat,
    'stepsEn' : IDL.Vec(IDL.Text),
    'stepsHi' : IDL.Vec(IDL.Text),
    'cuisine' : Cuisine,
    'category' : Category,
    'prepTimeMinutes' : IDL.Nat,
    'servings' : IDL.Nat,
    'titleEn' : IDL.Text,
    'titleHi' : IDL.Text,
    'ingredientsEn' : IDL.Vec(IDL.Text),
    'ingredientsHi' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          Cuisine,
          Category,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [Recipe],
        [],
      ),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getRecipe' : IDL.Func([RecipeID], [Recipe], ['query']),
    'getRecipesByCategory' : IDL.Func([Category], [IDL.Vec(Recipe)], ['query']),
    'getRecipesByCuisine' : IDL.Func([Cuisine], [IDL.Vec(Recipe)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };