/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'sideDish' : null } |
  { 'mainCourse' : null } |
  { 'dessert' : null } |
  { 'soup' : null } |
  { 'salad' : null } |
  { 'appetizer' : null } |
  { 'beverage' : null };
export type Cuisine = { 'mediterranean' : null } |
  { 'thai' : null } |
  { 'japanese' : null } |
  { 'chinese' : null } |
  { 'mexican' : null } |
  { 'italian' : null } |
  { 'indian' : null } |
  { 'spanish' : null } |
  { 'american' : null } |
  { 'french' : null };
export interface Recipe {
  'id' : RecipeID,
  'photoAssetPath' : string,
  'descriptionEn' : string,
  'descriptionHi' : string,
  'createdAt' : Time,
  'cookTimeMinutes' : bigint,
  'stepsEn' : Array<string>,
  'stepsHi' : Array<string>,
  'cuisine' : Cuisine,
  'category' : Category,
  'prepTimeMinutes' : bigint,
  'servings' : bigint,
  'titleEn' : string,
  'titleHi' : string,
  'ingredientsEn' : Array<string>,
  'ingredientsHi' : Array<string>,
}
export type RecipeID = bigint;
export type Time = bigint;
export interface _SERVICE {
  'addRecipe' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      Cuisine,
      Category,
      bigint,
      bigint,
      bigint,
      string,
    ],
    Recipe
  >,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getRecipe' : ActorMethod<[RecipeID], Recipe>,
  'getRecipesByCategory' : ActorMethod<[Category], Array<Recipe>>,
  'getRecipesByCuisine' : ActorMethod<[Cuisine], Array<Recipe>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];