/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type RecipeID = bigint;
export interface Recipe {
    id: RecipeID;
    photoAssetPath: string;
    descriptionEn: string;
    descriptionHi: string;
    createdAt: Time;
    cookTimeMinutes: bigint;
    stepsEn: Array<string>;
    stepsHi: Array<string>;
    cuisine: Cuisine;
    category: Category;
    prepTimeMinutes: bigint;
    servings: bigint;
    titleEn: string;
    titleHi: string;
    ingredientsEn: Array<string>;
    ingredientsHi: Array<string>;
}
export type Time = bigint;
export enum Category {
    sideDish = "sideDish",
    mainCourse = "mainCourse",
    dessert = "dessert",
    soup = "soup",
    salad = "salad",
    appetizer = "appetizer",
    beverage = "beverage"
}
export enum Cuisine {
    mediterranean = "mediterranean",
    thai = "thai",
    japanese = "japanese",
    chinese = "chinese",
    mexican = "mexican",
    italian = "italian",
    indian = "indian",
    spanish = "spanish",
    american = "american",
    french = "french"
}
export interface backendInterface {
    addRecipe(titleEn: string, titleHi: string, descriptionEn: string, descriptionHi: string, ingredientsEn: Array<string>, ingredientsHi: Array<string>, stepsEn: Array<string>, stepsHi: Array<string>, cuisine: Cuisine, category: Category, prepTimeMinutes: bigint, cookTimeMinutes: bigint, servings: bigint, photoAssetPath: string): Promise<Recipe>;
    getAllRecipes(): Promise<Array<Recipe>>;
    getRecipe(id: RecipeID): Promise<Recipe>;
    getRecipesByCategory(category: Category): Promise<Array<Recipe>>;
    getRecipesByCuisine(cuisine: Cuisine): Promise<Array<Recipe>>;
}
import type { Category as _Category, Cuisine as _Cuisine, Recipe as _Recipe, RecipeID as _RecipeID, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRecipe(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: Array<string>, arg6: Array<string>, arg7: Array<string>, arg8: Cuisine, arg9: Category, arg10: bigint, arg11: bigint, arg12: bigint, arg13: string): Promise<Recipe> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_Cuisine_n1(this._uploadFile, this._downloadFile, arg8), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12, arg13);
                return from_candid_Recipe_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_Cuisine_n1(this._uploadFile, this._downloadFile, arg8), to_candid_Category_n3(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12, arg13);
            return from_candid_Recipe_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecipes(): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecipes();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecipes();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipe(arg0: RecipeID): Promise<Recipe> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return from_candid_Recipe_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return from_candid_Recipe_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipesByCategory(arg0: Category): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipesByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipesByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipesByCuisine(arg0: Cuisine): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipesByCuisine(to_candid_Cuisine_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipesByCuisine(to_candid_Cuisine_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Cuisine_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cuisine): Cuisine {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Recipe_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recipe): Recipe {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecipeID;
    photoAssetPath: string;
    descriptionEn: string;
    descriptionHi: string;
    createdAt: _Time;
    cookTimeMinutes: bigint;
    stepsEn: Array<string>;
    stepsHi: Array<string>;
    cuisine: _Cuisine;
    category: _Category;
    prepTimeMinutes: bigint;
    servings: bigint;
    titleEn: string;
    titleHi: string;
    ingredientsEn: Array<string>;
    ingredientsHi: Array<string>;
}): {
    id: RecipeID;
    photoAssetPath: string;
    descriptionEn: string;
    descriptionHi: string;
    createdAt: Time;
    cookTimeMinutes: bigint;
    stepsEn: Array<string>;
    stepsHi: Array<string>;
    cuisine: Cuisine;
    category: Category;
    prepTimeMinutes: bigint;
    servings: bigint;
    titleEn: string;
    titleHi: string;
    ingredientsEn: Array<string>;
    ingredientsHi: Array<string>;
} {
    return {
        id: value.id,
        photoAssetPath: value.photoAssetPath,
        descriptionEn: value.descriptionEn,
        descriptionHi: value.descriptionHi,
        createdAt: value.createdAt,
        cookTimeMinutes: value.cookTimeMinutes,
        stepsEn: value.stepsEn,
        stepsHi: value.stepsHi,
        cuisine: from_candid_Cuisine_n7(_uploadFile, _downloadFile, value.cuisine),
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        prepTimeMinutes: value.prepTimeMinutes,
        servings: value.servings,
        titleEn: value.titleEn,
        titleHi: value.titleHi,
        ingredientsEn: value.ingredientsEn,
        ingredientsHi: value.ingredientsHi
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sideDish: null;
} | {
    mainCourse: null;
} | {
    dessert: null;
} | {
    soup: null;
} | {
    salad: null;
} | {
    appetizer: null;
} | {
    beverage: null;
}): Category {
    return "sideDish" in value ? Category.sideDish : "mainCourse" in value ? Category.mainCourse : "dessert" in value ? Category.dessert : "soup" in value ? Category.soup : "salad" in value ? Category.salad : "appetizer" in value ? Category.appetizer : "beverage" in value ? Category.beverage : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mediterranean: null;
} | {
    thai: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    mexican: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    spanish: null;
} | {
    american: null;
} | {
    french: null;
}): Cuisine {
    return "mediterranean" in value ? Cuisine.mediterranean : "thai" in value ? Cuisine.thai : "japanese" in value ? Cuisine.japanese : "chinese" in value ? Cuisine.chinese : "mexican" in value ? Cuisine.mexican : "italian" in value ? Cuisine.italian : "indian" in value ? Cuisine.indian : "spanish" in value ? Cuisine.spanish : "american" in value ? Cuisine.american : "french" in value ? Cuisine.french : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recipe>): Array<Recipe> {
    return value.map((x)=>from_candid_Recipe_n5(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Cuisine_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cuisine): _Cuisine {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cuisine): {
    mediterranean: null;
} | {
    thai: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    mexican: null;
} | {
    italian: null;
} | {
    indian: null;
} | {
    spanish: null;
} | {
    american: null;
} | {
    french: null;
} {
    return value == Cuisine.mediterranean ? {
        mediterranean: null
    } : value == Cuisine.thai ? {
        thai: null
    } : value == Cuisine.japanese ? {
        japanese: null
    } : value == Cuisine.chinese ? {
        chinese: null
    } : value == Cuisine.mexican ? {
        mexican: null
    } : value == Cuisine.italian ? {
        italian: null
    } : value == Cuisine.indian ? {
        indian: null
    } : value == Cuisine.spanish ? {
        spanish: null
    } : value == Cuisine.american ? {
        american: null
    } : value == Cuisine.french ? {
        french: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    sideDish: null;
} | {
    mainCourse: null;
} | {
    dessert: null;
} | {
    soup: null;
} | {
    salad: null;
} | {
    appetizer: null;
} | {
    beverage: null;
} {
    return value == Category.sideDish ? {
        sideDish: null
    } : value == Category.mainCourse ? {
        mainCourse: null
    } : value == Category.dessert ? {
        dessert: null
    } : value == Category.soup ? {
        soup: null
    } : value == Category.salad ? {
        salad: null
    } : value == Category.appetizer ? {
        appetizer: null
    } : value == Category.beverage ? {
        beverage: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
